# Site settings
title: Open Digital Humanities Notebook
description: "An open history notebook forked from Jason Heppler"
baseurl: ""
url: "http://smgprojects.github.io"
root: /
highlighter: pygments
gems: ['jekyll/scholar']
permalink: /:title/
repo: notebook

source: source
destination: public
exclude: ["Rakefile", "README.md", "public"]

# Author information
author:
  name: Shawn Graham
  givenName: Shawn
  familyName: Graham
  avatar: minionme.jpeg
  email: shawn.graham@carleton.ca
  twitter_username: electricarchaeo
  github_username:  shawngraham
  homeurl: http://electricarchaeology.ca

# Scholar settings
scholar:
  style: chicago-fullnote-bibliography
  source: ./_bibliography
  bibliography: bibliography.bib

# Build settings
destination: public
markdown: kramdown
# pandoc:
#   extensions:
#     - smart
markdown_ext:  markdown,mkdown,mkdn,mkd,md,Rmd,rmd
exclude: ['Makefile', 'Rakefile', '_drafts']
